#!/usr/bin/env python3
# ProsperoEden - Bake the loading screen's "LOADING" wordmark into a GLSL distance field.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes headless/loading_wordmark.glsl: the word in Montserrat Medium as a small signed
distance field packed into a constant array, so the loading shader needs no texture.

The field is WIDTH x HEIGHT texels, one byte each (four per uint, low byte first, top row first):
128 on the outline, 255 SPREAD texels inside, 0 SPREAD texels outside.
"""

from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
FONT = ROOT / "third_party/fonts/Montserrat-Medium.ttf"
OUTPUT = ROOT / "headless/loading_wordmark.glsl"

TEXT = "LOADING"
WIDTH, HEIGHT = 176, 28   # texels
SPREAD = 4.0              # texels of distance stored each side of the outline
SCALE = 8                 # the word is drawn this much larger, then measured
TRACKING = 0.22           # extra space between letters, in ems
MARGIN = 5                # texels kept clear around the word


def draw_word():
    """The word as a boolean mask SCALE times the field's size."""
    width, height = WIDTH * SCALE, HEIGHT * SCALE
    cap = (HEIGHT - 2 * MARGIN) * SCALE  # capital height in pixels
    size = round(cap / 0.70)             # Montserrat capitals are 0.70 em
    font = ImageFont.truetype(str(FONT), size)
    advances = [font.getlength(letter) for letter in TEXT]
    total = sum(advances) + TRACKING * size * (len(TEXT) - 1)
    image = Image.new("L", (width, height))
    draw = ImageDraw.Draw(image)
    x = (width - total) / 2
    baseline = (height + cap) / 2
    for letter, advance in zip(TEXT, advances):
        draw.text((x, baseline), letter, font=font, fill=255, anchor="ls")
        x += advance + TRACKING * size
    used = total / width
    assert used < 1 - 2 * MARGIN / WIDTH, f"the word needs a wider field ({used:.2f})"
    return np.asarray(image) >= 128


def distance_field(mask):
    """Signed distance to the outline in field texels, sampled at texel centres."""
    inside_points = np.argwhere(mask)
    outside_points = np.argwhere(~mask)
    # Only pixels next to the other side can be nearest: keep the outline pixels.
    padded = np.pad(mask, 1, mode="edge")
    neighbours = (padded[:-2, 1:-1] & padded[2:, 1:-1] & padded[1:-1, :-2] & padded[1:-1, 2:])
    edge_inside = np.argwhere(mask & ~neighbours).astype(np.float32)
    any_outside = (~padded[:-2, 1:-1]) & (~padded[2:, 1:-1]) & (~padded[1:-1, :-2]) & (~padded[1:-1, 2:])
    edge_outside = np.argwhere(~mask & ~any_outside).astype(np.float32)
    del inside_points, outside_points
    ys = (np.arange(HEIGHT) + 0.5) * SCALE - 0.5
    xs = (np.arange(WIDTH) + 0.5) * SCALE - 0.5
    field = np.zeros((HEIGHT, WIDTH), np.float32)
    for row, y in enumerate(ys):
        points = np.stack([np.full(WIDTH, y, np.float32), xs.astype(np.float32)], axis=1)
        to_inside = np.sqrt(((points[:, None, :] - edge_inside[None, :, :]) ** 2).sum(-1)).min(1)
        to_outside = np.sqrt(((points[:, None, :] - edge_outside[None, :, :]) ** 2).sum(-1)).min(1)
        is_inside = mask[np.clip(np.round(y).astype(int), 0, mask.shape[0] - 1),
                         np.clip(np.round(xs).astype(int), 0, mask.shape[1] - 1)]
        field[row] = np.where(is_inside, to_outside, -to_inside) / SCALE
    return field


def main():
    field = distance_field(draw_word())
    data = np.clip(np.round(128 + field / SPREAD * 127), 0, 255).astype(np.uint32).reshape(-1)
    assert data.size % 4 == 0
    words = data[0::4] | (data[1::4] << 8) | (data[2::4] << 16) | (data[3::4] << 24)
    lines = [
        "// Generated by tools/launcher/bake-wordmark.py from Montserrat Medium (SIL Open Font",
        "// License 1.1). Do not edit: change the script and run it again.",
        f"const int kWordWidth = {WIDTH};",
        f"const int kWordHeight = {HEIGHT};",
        f"const float kWordSpread = {SPREAD:.1f};",
        f"const uint kWord[{words.size}] = uint[{words.size}](",
    ]
    for start in range(0, words.size, 8):
        chunk = ", ".join(f"0x{value:08x}u" for value in words[start:start + 8])
        lines.append("    " + chunk + ("," if start + 8 < words.size else ""))
    lines.append(");")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUTPUT.name}: {WIDTH}x{HEIGHT} texels, {words.size} words, "
          f"inside {int((field > 0).sum())} texels")


if __name__ == "__main__":
    main()
